// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordEmail.Context;

#nullable disable

namespace RecordEmail.Migrations
{
    [DbContext(typeof(EmailCadastroBdContext))]
    partial class EmailCadastroBdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LegisOn.DAL.Models.Ato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAto")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRepublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ementa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdIniciativa")
                        .HasColumnType("int");

                    b.Property<int?>("IdParecer")
                        .HasColumnType("int");

                    b.Property<int?>("IdSituacao")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoAto")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoOrigem")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCriador")
                        .HasColumnType("int");

                    b.Property<int?>("Inteiro")
                        .HasColumnType("int");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MensagemGovernamental")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroOrigem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PalavrasChave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdParecer");

                    b.ToTable("Atos");
                });

            modelBuilder.Entity("RecordEmail.Models.Email", b =>
                {
                    b.Property<int>("IdEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EnderecoEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModificadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenDeVerificacao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Verificado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("VerificadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdEmail");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("LegisOn.DAL.Models.Ato", b =>
                {
                    b.HasOne("LegisOn.DAL.Models.Ato", "Parecer")
                        .WithMany()
                        .HasForeignKey("IdParecer");

                    b.Navigation("Parecer");
                });
#pragma warning restore 612, 618
        }
    }
}
